### ISSUE TITLE
Cannot delete dashboards with invalid JSON

### ISSUE THREAD

**Issue by simwak** [grafana/crossplane-provider-grafana#105]
A dashboard that was first successfully created with a valid JSON cannot be deleted after it has been updated with an invalid JSON.

## Steps to reproduce
1. Create dashboard with:
``` yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  name: test-dashboard
spec:
  forProvider:
    configJson: |
      {
        "title": "Crossplane Test!",
        "uid": "crossplane"
      }
  providerConfigRef:
    name: default
```` 
2. Update it with:
``` yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  name: test-dashboard
spec:
  forProvider:
    configJson: |
      {
        "title": "Crossplane Test!",
        "uid": "crossplane"
  providerConfigRef:
    name: default
```` 
3. `kubectl delete dashboard test-dashboard`

The deletion is stuck until it is updated again with valid JSON. I would expect it to use the referenced dashboard that was last successfully applied (`status.atProvider.id`) and delete it.
