### ISSUE TITLE
org_id is only supported with basic auth. API keys are already org-scoped

### ISSUE THREAD

**Issue by Hronom** [grafana/crossplane-provider-grafana#144]
Hello, is there was some recent changes in grafana cloud?
We start getting error:
```
    - lastTransitionTime: '2024-05-13T15:15:31Z'
      message: >-
        create failed: failed to create the resource: [{0 org_id is only
        supported with basic auth. API keys are already org-scoped  []}]
      reason: ReconcileError
      status: 'False'
      type: Synced
```
Version: v0.14.1
Same also in v0.16.1

**Comment by Hronom** [comment]
Seems like deletion of `orgId: "1"` in configs helps.
For example I deleted in `dashboard` and it start work.

Old:
```
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  name: ...
spec:
  forProvider:
    orgId: "1"
    folder: ...
    configJson: ...
    overwrite: true
  providerConfigRef:
    name: ...
```

New:
```
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  name: ...
spec:
  forProvider:
    folder: ...
    configJson: ...
    overwrite: true
  providerConfigRef:
    name: ...
```
