### ISSUE TITLE
Cannot create sso config

### ISSUE THREAD

**Issue by ksawerykarwacki** [grafana/crossplane-provider-grafana#152]
I tried to create sso config in Grafana Cloud:

```
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: SsoSettings
metadata:
  name: test-sso
spec:
  forProvider:
    oauth2Settings:
      - authUrl: https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize
        tokenUrl: https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token
        scopes: openid,email,profile
        name: Microsoft
        clientId: CLIENT_ID
        clientSecretSecretRef:
          key: CLIENT_SECRET
          name: azuread-secret
          namespace: observability
    providerName: azuread
  providerConfigRef:
    name: test-test
```

Using service account I get:

```
create failed: failed to create the resource: [{0 failed to create the
        SSO settings for provider azuread: [PUT /v1/sso-settings/{key}][401]
        updateProviderSettingsUnauthorized {"message":"Unauthorized"}  []}]
```

Using access policy token I get:

```
 create failed: failed to create the resource: [{0 the Grafana client is
        required for this resource. Set the auth and url provider attributes 
        []}]
```

I tried both global access policy with full scope for:  `stack-oauth` and `oauth-clients`

And stack specific access policy with  full scope for `stack-oauth`

Cloud Service account was set to Admin role.
