### ISSUE TITLE
Contact Point for MS Teams fails to update URL

### ISSUE THREAD

**Issue by sachinmalanki** [grafana/crossplane-provider-grafana#184]
Hi,

Provider version - `provider-grafana:v0.18.0`
Contact point for MS Teams seems to fail when updating the teams URL. 
```
apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: ContactPoint
metadata:
  annotations:
    meta.upbound.io/example-id: alerting/v1alpha1/notificationpolicy
  labels:
    testing.upbound.io/example-name: test_contact_point_teams
  name: test-contact-point-teams
spec:
  forProvider:
    teams:
    - disableResolveMessage: false
      title: '{{ template "default.title" .}}'
      message: |
        [{{ .Status | toUpper}}] Alert Notification

        There are {{ len .Alerts.Firing }} firing alerts and {{ len .Alerts.Resolved }} resolved alerts.
        
        **Alert Details:**
        - **Name:** {{ .CommonLabels.alertname }}
        - **Severity:** {{ .CommonLabels.severity }}
        - **Summary:** {{ .CommonAnnotations.summary }}
        - **Description:** {{ .CommonAnnotations.description }}

        **Links:**
        - 📚 [Runbooks]({{ .CommonAnnotations.Runbook }})
        - 🔬 [Query](<grafana-query-link>)
        - 📊 [Dashboard]({{ .CommonAnnotations.dashboard_url }})
        - 🔕 [Silence]{{ end }}{{ if gt (len .SilenceURL) 0 }}Silence: {{ .SilenceURL }}

        **Additional Context:**
        - **Affected Systems:** {{ .CommonLabels.instance }}
        - **Environment:** {{ .Labels.environment }}
        - **Alert Source:** {{ .GeneratorURL }}
        
      sectionTitle: '{{ template "default.title" .}}'
      urlSecretRef:
        key: msteams-webhook-url
        name: cp-grafana-credentials
        namespace: observability
    name: Contact Point MS Teams
  providerConfigRef:
    name: grafana-oss-provider 
```

Getting the following error  - 

`failed to create the resource: [{0 [POST /v1/provisioning/contact-points][400] postContactpointsBadRequest {"message":"invalid object specification: failed to validate integration \"Contact Point MS Teams\" (UID ) of type \"teams\": could not find url property in settings"} []}]`

Looks like the MR looks for a `url` but there from the CRD it expects a `urlSecretRef`. 
Could you please help fix this issue?
