### ISSUE TITLE
Switch to datasourceRef on DataSourcePermission

### ISSUE THREAD

**Issue by yehlo** [grafana/crossplane-provider-grafana#191]
Hi

Currently the spec requires a manually read UID through the spec.
```yaml
apiVersion: enterprise.grafana.crossplane.io/v1alpha1
kind: DataSourcePermission
metadata:
  name: datasource-permissions
spec:
  forProvider:
    datasourceUid: ${grafana_data_source.foo.uid}
```
see also: 
https://github.com/grafana/crossplane-provider-grafana/blob/main/apis/enterprise/v1alpha1/zz_datasourcepermission_types.go#L20 

I'm not sure how smart it is to edit the controller-code considering it's from the terraform-provider but with the current implementation you are required to lookup the id from the datasource.status.atProvider.uid field.

I think the provider should do this according to the rest of the resources using a ref. 
Or am I maybe missing something? 

For now I will just use a composition to make this work.

Thx & regards
