### ISSUE TITLE
Make orgId part of ProviderConfig

### ISSUE THREAD

**Issue by abacus3** [grafana/crossplane-provider-grafana#2]
### What problem are you facing?

The current implementation in https://github.com/grafana/crossplane-provider-grafana/blob/main/internal/clients/grafana.go extracts the orgId used to configure the provider from the k8s secret referenced in the respective `ProviderConfig` . \
When reconciling resources within an organization, an appropriate `ProviderConfig` and separate secret have to be created. \
This would result in the creation of individual secrets for each provider, decreasing the flexibility in configurting this provider in a multi-tenant fashion. \
The major limiting factor with this approach is that the provider can not extract, process and re-use the secret's JSON payload in order to create new, organization specific `ProviderConfig` instances.

If the `orgId` would not be part of the secret's JSON payload it would be referencable in compositions, hence increasing flexibility during the dynamic management of organizations and respective managed resources within them.

### How could Grafana Provider help solve your problem?

In order to improve this situation, I'd propose to exclude the orgId from the actual secret and make it part of the `ProviderConfig` definition directly, allowing us to specify the same secret for different `ProviderConfig` resource instances while adressing different `orgId`s.

The proposed `ProviderConfig` would look like this:
```
apiVersion: grafana.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  orgId: 1
  credentials:
    source: Secret
    secretRef:
      name: grafana-creds
      namespace: crossplane
      key: credentials

```

I can offer to create a PR for this potential feature.
