### ISSUE TITLE
Any plans to make compatible with Grizzly export?

### ISSUE THREAD

**Issue by mikaello** [grafana/crossplane-provider-grafana#218]
The [Grizzly project](https://github.com/grafana/grizzly/) can export K8S style manifests, e.g., a dashboard could look like this when exported with `grr export`:

```yaml
apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
    folder: general
    name: my-example-dashboard
spec:
    annotations: {}
    description: My example dashboard
    editable: true
    panels:
      ...
```

In this projects, resources uses another `apiVersion` and spec, example

```yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/dashboard
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    configJson: |-
      ${jsonencode({
          "title" : "My Dashboard",
          "uid" : "my-dashboard-uid"
        })}
  ...
```

Grizzly currently (v0.6.1) supports the following providers:

```
$ grr providers
API VERSION                     KIND
grizzly.grafana.com/v1alpha1    Datasource
grizzly.grafana.com/v1alpha1    DashboardFolder
grizzly.grafana.com/v1alpha1    LibraryElement
grizzly.grafana.com/v1alpha1    Dashboard
grizzly.grafana.com/v1alpha1    AlertRuleGroup
grizzly.grafana.com/v1alpha1    AlertNotificationPolicy
grizzly.grafana.com/v1alpha1    AlertContactPoint
grizzly.grafana.com/v1alpha1    PrometheusRuleGroup
grizzly.grafana.com/v1alpha1    SyntheticMonitoringCheck
```

Could this project and Grizzly potentially be compatible in a way that allows the resources generated by Grizzly to be consumed by this Crossplane provider? We are currently using Grizzly with K8S style manifests and deploying them with `grr apply`. However, we would really like to use this provider. It would be fantastic if we could continue developing our dashboards with Grizzly and simply change the deployment step.

Or is it any thought on how to combine Grizzly and this provider?
