### ISSUE TITLE
Unable to set parent folder uid on newly created folder

### ISSUE THREAD

**Issue by tylerauerbeck** [grafana/crossplane-provider-grafana#230]
### Crossplane Version

1.18.2

### Crossplane Grafana Provider Version

0.23.0 

### Affected Resource(s)

oss.grafana.crossplane.io/v1alpha1/Folder

### YAML resources

```yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: my-team-folder
spec:
  forProvider:
    title: My Team
    uid: my-team
    preventDestroyIfNotEmpty: true
    parentFolderUid: my-larger-team
  providerConfigRef:
    name: grafana.local
```

### Expected Behavior

On initial creation, I expect to be able to create a folder that references a parent folder UID so that it is contained within this parent folder. However, I receive a message that it's not able to update this field as it appears it creates the folder first and then attempts to update the parent folder uid field and it is then immutable after that initial creation.

```
    Message:               update failed: refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "parent_folder_uid" from "" to "my-larger-team"
```

### Actual Behavior

Child folder creation failed. A folder is created, but it does not exist under the desired parent folder.

### Steps to Reproduce

Apply the above to a cluster running Crossplane v1.18.2 and grafana provider 0.23.0

### Important Factoids

Kubernetes v1.30

### References

Unsure if this field is just not expected to work at all via Crossplane per https://github.com/grafana/crossplane-provider-grafana/issues/148
