### ISSUE TITLE
DataSources canot be created with Tokens from AccessPolicyToken

### ISSUE THREAD

**Issue by transacid** [grafana/crossplane-provider-grafana#238]
### Crossplane Version

v1.15.2-up.1

### Crossplane Grafana Provider Version

v0.24.1

### Affected Resource(s)

* oss.grafana.crossplane.io/v1alpha1/datasources
* cloud.grafana.crossplane.io/v1alpha1/accesspolicytokens

### YAML resources

```yaml
apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: AccessPolicyToken
metadata:
  name: sandbox-cap-ns-metrics
spec:
  forProvider:
    accessPolicySelector:
      matchLabels:
        cap-name: sandbox-cap-ns-metrics
    name: sandbox-cap-ns-metrics
    region: prod-eu-west-2
  writeConnectionSecretToRef:
    name: sandbox-cap-ns-metrics-token
    namespace: crossplane-system
  providerConfigRef:
    name: sandbox-cap-manager
```

```yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: DataSource
metadata:
  labels:
    cap-name: sandbox-cap-ns-metrics
  name: prometheus-sandbox-ns-metrics
spec:
  forProvider:
    name: prometheus-sandbox-ns-metrics
    type: prometheus
    url: "https://XXXXXXXXX.grafana.net/api/prom"
    basicAuthEnabled: true
    basicAuthUsername: "XXXXXXXX"
    jsonDataEncoded: |
      {
        "httpMethod": "POST",
        "tokenName": "sandbox-cap-ns-metrics"
      }
    secureJsonDataEncodedSecretRef:
      key: attribute.token                                   # this is the field in question
      name: sandbox-cap-ns-metrics-token-manual
      namespace: crossplane-system
  providerConfigRef:
    name: sandbox-stack
```

```yaml
apiVersion: v1
data:
  attribute.token: dG9rZW5fY29udGVudA==.                                         # token_content
  cloudCredentials: eyJjbG91ZF9hY2Nlc3NfcG9saWN5X3Rva2VuIjoidG9rZW5fY29udGVudCJ9 # {"cloud_access_policy_token":"token_content"}
kind: Secret 
metadata:
  name: sandbox-cap-ns-metrics-token
type: connection.crossplane.io/v1alpha1
```

### Expected Behavior

the ConnectionSecret rendered by `AccessPolicyToken` should reflect the json syntax that is needed for `DataSource` `secureJsonDataEncodedSecretRef`.
for a prometheus datasource the format would need to be `{"basicAuthPassword": "toke_content"}`

### Actual Behavior

currently the ConnectionSecret rendered by `AccessPolicyToken` renders a secret with the fields `attribute.token` (which just holds the toke) and `cloudCredentials` (which holds a json string of the format `{"cloud_access_policy_token":"token_content"}`.
for a prometheus datasource the format would need to be `{"basicAuthPassword": "toke_content"}`

### Steps to Reproduce

apply AccessPolicyToken and DataSource.
