### ISSUE TITLE
[Feature] Add a dashboard id field to download dashboards from grafana dashoards site.

### ISSUE THREAD

**Issue by hayone1** [grafana/crossplane-provider-grafana#245]
### Feature Request

Some people may want to use the dashboards provided in the [grafana online dashboards](https://grafana.com/grafana/dashboards) without altering it so it would be nice just to be able to specify the dashboard ID similar to how you can import that in the grafana UI.

Currently, I use something like the below which would all go away specifying the id in the `Dashboard` resource was enough.

``` yaml
# ./base/minio-grafana-dashboard.yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  name: minio-grafana-dashboard
  annotations:
    config.grafana.com/dashboard-id: '13502'
  labels:
    meta.upbound.io/name: minio-grafana-dashboard
spec:
  forProvider:
    folderSelector:
      matchLabels:
        meta.upbound.io/name: observability-stack-folder
    configJson: |-
      will be replaced by shell/kustomize
```

In combination with a script like the below:
``` shell
# get-dashboards.sh
for file in ./base/*-grafana-dashboard.yaml; do
  if [[ -f "$file" ]]; then
    manifest_filename=$(basename "$file")
    dashboard_id=$(yq '.metadata.annotations."config.grafana.com/dashboard-id"' "$file")
    latest_revision=$(curl https://grafana.com/api/dashboards/${dashboard_id}/revisions | jq '[.items[].revision] | max')

    dashboard_config_filepath="${file/.yaml/.json}"
    wget "https://grafana.com/api/dashboards/${dashboard_id}/revisions/${latest_revision}/download" \
        -O  "$dashboard_config_filepath"
# example of RUN_ENVIRONMENT will be 'production'
    yq -i '.spec.forProvider.configJson |= (load("'"${dashboard_config_filepath}"'") | to_json)' "./overlays/${RUN_ENVIRONMENT}/${manifest_filename}"
  fi
done
```
