### ISSUE TITLE
Not able to provision dashboard with crossplane grafana provider

### ISSUE THREAD

**Issue by shankar-bala** [grafana/crossplane-provider-grafana#248]
### Crossplane Version

v1.14.2

### Crossplane Grafana Provider Version

xpkg.upbound.io/grafana/provider-grafana:v0.25.0

### Affected Resource(s)

* oss.grafana.crossplane.io/v1alpha1/Dashboard

### YAML resources

```

apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: grafana-provider-config
spec:
  credentials:
    secretRef:
      key: auth
      name: grafana-secret
      namespace: crossplane
    source: Secret
  url: https://local-grafana-url.com
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-grafana
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/grafana/provider-grafana:v0.25.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
---
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  name: first-dashboard
spec:
  forProvider:
    configJson: |
      {
        "title": "First dashboard",
        "uid": "first-dashboard"
      }
  providerConfigRef:
    name: grafana-provider-config

```
kubernetes secret `grafana-secret` content 

```
{
    "auth": "admin:testing"
}
```

### Expected Behavior

Expected dashboard showing up in the grafana UI.. 

### Actual Behavior

when looked at the status of `Dashboard` object., i see this error

```
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2025-02-20T23:18:30Z"
    message: 'connect failed: cannot get terraform setup: cannot unmarshal grafana
      credentials as JSON: unexpected end of JSON input'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### Steps to Reproduce

1. Create secret object and apply the above yaml files

**Comment by Duologic** [comment]
The provider secret value needs to look like this:

```json
{
  "auth": "<token>",
  "url": "<grafanaURL>"
}
```

Assuming your secret object looks like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: crossplane
type: Opaque
data:
  auth: <base64>
```
