### ISSUE TITLE
Removing last entry of viewers or editors results in "null" issue

### ISSUE THREAD

**Issue by kkendzia** [grafana/crossplane-provider-grafana#291]
### Crossplane Version

1.18.3

### Crossplane Grafana Provider Version

0.26.0

### Affected Resource(s)

* oss.grafana.crossplane.io/Organization/v1alpha1

### YAML resources

Inside of Composition Function at first we compose

```yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    admins:
      - some_admin_user_email@example.com
    editors: []
    name: cnp-example
    viewers:
      - some_viewer_user_email@example.com
  providerConfigRef:
    name: default
```

after this we change the composite to remove the viewers

```yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    admins:
      - some_admin_user_email@example.com
    editors: []
    name: cnp-example
    viewers: []
  providerConfigRef:
    name: default
```

### Expected Behavior

viewers in managed resource and on grafana server should be empty

### Actual Behavior

With server side apply values get merged and not overwritten. 
x-kubernetes-list-type: set seems to be the issue here, setting it to atomic we had no issues.

Also we (sometimes, randomly) ran into the error:
defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot apply composed resource "organization": Organization.oss.grafana.crossplane.io "example-dev" is invalid: [spec.forProvider.viewers: Invalid value: "null": spec.forProvider.viewers in body must be of type array: "null", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]

**Comment by Duologic** [comment]
Seems similar to #282

**Comment by kkendzia** [comment]
Seems similar, we observed the same behaviour in 0.18.0 on a different cluster, too.

What bothers most is, that due to "x-kubernetes-list-type: set" the merge behaviour and SSA is pretty strange. I couldn't remove the last viewer email - managedFields of this entry seems to merge with the incoming change, which is pretty unusual behaviour.

**Comment by kkendzia** [comment]
Replication:

org.yaml
```yaml
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    adminUser: admin
    admins:
    - some@email.com
    createUsers: true
    editors: []
    name: example
    viewers: []
  initProvider: {}
  providerConfigRef:
    name: default
```

```bash
k apply -f org.yaml --server-side=true 

kubectl proxy

curl -vv -X PATCH \
  "http://127.0.0.1:8001/apis/oss.grafana.crossplane.io/v1alpha1/organizations/example?fieldManager=ssa-manager&force=true" \
  -H "Content-Type: application/apply-patch+yaml" \
  --data-binary @- <<EOF
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: example
spec:
  forProvider:
    viewers: ["test"]
EOF

# Wait some time

curl -vv -X PATCH \
  "http://127.0.0.1:8001/apis/oss.grafana.crossplane.io/v1alpha1/organizations/example?fieldManager=ssa-manager&force=true" \
  -H "Content-Type: application/apply-patch+yaml" \
  --data-binary @- <<EOF
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: example
spec:
  forProvider:
    viewers: []
EOF

k get -f org.yaml --show-managed-fields -oyaml
```

Result: unable to remove "test" from viewers as it's added back by the provider.
``` yaml
  - apiVersion: oss.grafana.crossplane.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:crossplane.io/external-create-pending: {}
          f:crossplane.io/external-create-succeeded: {}
          f:crossplane.io/external-name: {}
        f:finalizers:
          .: {}
          v:"finalizer.managedresource.crossplane.io": {}
      f:spec:
        f:forProvider:
          f:viewers:
            .: {}
            v:"test": {}
    manager: provider
    operation: Update
    time: "2025-05-14T06:56:33Z"
```
