### ISSUE TITLE
Document ProviderConfig fields and secret parameters

### ISSUE THREAD

**Issue by Duologic** [grafana/crossplane-provider-grafana#300]
The fields of the ProviderConfig are documented as [published on the marketplace](https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.28.0/resources/grafana.crossplane.io/ProviderConfig/v1beta1) but the required secret values are a bit opaque. 

The code for them is here: https://github.com/grafana/crossplane-provider-grafana/blob/main/internal/clients/grafana.go#L62

Example from #248:

--- 
The provider secret value needs to look like this:

```json
{
  "auth": "<token>",
  "url": "<grafanaURL>"
}
```

Assuming your secret object looks like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: crossplane
type: Opaque
data:
  auth: <base64>
```
