### ISSUE TITLE
Integer IDs are generated as string for k6 resources

### ISSUE THREAD

**Issue by yorugac** [grafana/crossplane-provider-grafana#307]
### Crossplane Grafana Provider Version

v0.28.0

### Affected Resource(s)

- k6.grafana.crossplane.io_loadtests.yaml
- k6.grafana.crossplane.io_projectlimits.yaml
- k6.grafana.crossplane.io_projects.yaml

### YAML resources

The definition of CRD contains an error so it doesn't matter which YAML is applied. E.g. applying the following:
```yaml
apiVersion: k6.grafana.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: k6/v1alpha1/installation
  labels:
    testing.upbound.io/example-name: my_k6_project
  name: my-k6-project
spec:
  forProvider:
    name: k6 Project created with TF
  providerConfigRef:
    name: grafana-cloud-provider
```
will result in this error:
```yaml
  conditions:
  - lastTransitionTime: "2025-05-29T12:22:07Z"
    message: 'connect failed: cannot construct dynamic value for TF state: cannot
      construct tf value from json: AttributeName("id"): error parsing number: EOF'
    reason: ReconcileError
    status: "False"
    type: Synced
```
AFAIS, no calls to the Cloud to sync the project are even made.

### Expected Behavior

Each definition of the 3 k6 CRDs should have `id` field set as integer type, as defined in Terraform provider. 

### Actual Behavior

All `id`s in the 3 k6 CRDs are generated as strings instead.

### Steps to Reproduce

CRD definitions are already part of the repo. They can be re-generated with `make generate` command repeating the same result.

### Important Factoids

The `id`s are expected to remain integers during generation or at least turn into a float due to this [upjet issue](https://github.com/crossplane/upjet/issues/442).

It's also noticeable that this doesn't happen to non-`id` fields like `project_id` [here](https://github.com/grafana/crossplane-provider-grafana/blob/365a752e0d5603a7546a7d1185d1cc2aee853641/apis/k6/v1alpha1/zz_loadtest_types.go#L52-L54) which indeed was generated as a float instead of integer. But `id`s are generated as strings making resources unusable.

### References

For example:
- [ID of project in TF provider](https://github.com/grafana/terraform-provider-grafana/blob/97b1dcabe530c764b1d8981f139e36f39161333c/internal/resources/k6/resource_project.go#L65-L68)
- [ID of project in Crossplane provider](https://github.com/grafana/crossplane-provider-grafana/blob/365a752e0d5603a7546a7d1185d1cc2aee853641/apis/k6/v1alpha1/zz_project_types.go#L33-L34)
