### ISSUE TITLE
how to cross reference team or user in folderpermission?

### ISSUE THREAD

**Issue by theblop** [grafana/crossplane-provider-grafana#52]
Is it possible to specify a team or user reference in the FolderPermission resource?

example:
```
...
---
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Team
metadata:
  name: testteam
spec:
  forProvider:
    name: "Test Team"
    memberRefs:
      - name: testuser
  providerConfigRef:
    name: crossplane-grafana-provider
---
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: testfolder
spec:
  forProvider:
    title: 'Crossplane Folder Test'
  providerConfigRef:
    name: crossplane-grafana-provider
---
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: FolderPermission
metadata:
  name: testfolder-permission
spec:
  forProvider:
    folderRef:
      name: testfolder
    permissions:
      - permission: "View"
        teamId: ${grafana_team.testteam.id}   # copied from (wrong?) generated example -> HOW TO REFERENCE the "testteam" team id ???????
  providerConfigRef:
    name: crossplane-grafana-provider
```

How can I dynamically resolve teamId? Or specify the team by reference?

I guess the generated example is wrong (it mentions a terraform cross reference variable `${grafana_team.testteam.id} `:
https://github.com/grafana/crossplane-provider-grafana/blob/main/examples-generated/oss/folderpermission.yaml
